In [24]:
import pandas as pd

In [32]:
country_mapping = {
    1: 'Belgium', 2: 'Denmark', 3: 'Germany', 4: 'Greece', 5: 'Spain',
    6: 'France', 7: 'Ireland', 8: 'Italy', 9: 'Netherlands', 10: 'United Kingdom',
    11: 'Portugal', 12: 'Austria', 13: 'Finland', 14: 'Sweden', 15: 'Bulgaria',
    16: 'Czech Republic', 17: 'Estonia', 18: 'Hungary', 19: 'Latvia', 20: 'Lithuania',
    21: 'Poland', 22: 'Romania', 23: 'Slovakia', 24: 'Slovenia', 25: 'Croatia',
    26: 'Malta', 27: 'Luxembourg', 28: 'Cyprus'
}

# Inverted mapping for searching by name
name_to_id = {name: id for id, name in country_mapping.items()}

In [44]:
       
df_ei = pd.read_csv("data/equaldex_equality_index-2024-dec.csv")
df_ei["country_id"] = df_ei["Name"].map(name_to_id)
df_ei = df_ei[["country_id", "EI Legal"]].dropna(subset=["country_id"]).reset_index(drop=True)
df_ei

    country_id  EI Legal
0          5.0       100
1          3.0       100
2          2.0        93
3          9.0        90
4         26.0       100
5         11.0        93
6          6.0        90
7         12.0        91
8          1.0        87
9         13.0        85
10        14.0        80
11         7.0        85
12        10.0        80
13         8.0        79
14        27.0        82
15         4.0        93
16        24.0        84
17        16.0        73
18        17.0        84
19        28.0        80
20        25.0        81
21        21.0        62
22        18.0        61
23        23.0        69
24        19.0        63
25        22.0        58
26        20.0        51
27        15.0        49

In [60]:
df_ess = pd.read_csv('data/ESS11e04_1.csv')
df_ess_cc = pd.read_csv('data/ess_country_codes.csv')

C:\Users\Jinal\AppData\Local\Temp\ipykernel_11016\1514334144.py:1: DtypeWarning: Columns (0: cntbrthd, 1: fbrncntc, 2: rinwe) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ess = pd.read_csv('data/ESS11e04_1.csv')

In [61]:
df_ess_cc.columns = df_ess_cc.columns.str.strip()
df_ess_cc.rename(columns={ "Value" : "cntry" }, inplace=True)

df_ess = pd.merge(df_ess, df_ess_cc, on='cntry', how='inner')
df_ess["country_id"] = df_ess["Category"].map(name_to_id)

df_ess["sclmeet_wg"] = df_ess["sclmeet"] * df_ess["anweight"]
df_ess["rlgblg_wg"] = df_ess["rlgblg"] * df_ess["anweight"]
df_ess["rlgdgr_wg"] = df_ess["rlgdgr"] * df_ess["anweight"]

df_ess = df_ess[["country_id", "sclmeet_wg", "rlgblg_wg", "rlgdgr_wg"]].groupby(by="country_id", as_index=False).mean()

df_ess

C:\Users\Jinal\AppData\Local\Temp\ipykernel_11016\2997220884.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_ess["country_id"] = df_ess["Category"].map(name_to_id)
C:\Users\Jinal\AppData\Local\Temp\ipykernel_11016\2997220884.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_ess["sclmeet_wg"] = df_ess["sclmeet"] * df_ess["anweight"]
C:\Users\Jinal\AppData\Local\Temp\ipykernel_11016\2997220884.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_ess["rlgblg_wg"] = df_ess["rlgblg"] * df_ess["anweight"]
C:\Users\Jinal\AppData\Local\Temp\ipykernel_11016\2997220884.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_ess["rlgdgr_wg"] = df_ess["rlgdgr"] * df_ess["anweight"]

    country_id  sclmeet_wg  rlgblg_wg  rlgdgr_wg
0          1.0    3.157097   0.991500   2.936396
1          3.0   14.698605   4.610831  11.842139
2          4.0    1.437598   0.355038   2.142735
3          5.0   11.847115   3.280645   9.778114
4          6.0   17.021128   4.967406  16.743310
5          7.0    0.917340   0.287844   1.088405
6          8.0    9.562802   2.366675  11.146709
7          9.0    4.903379   1.549470   3.718741
8         10.0   15.959060   5.371748  12.915207
9         11.0    3.773638   0.865315   3.998501
10        12.0    1.656219   0.453005   1.621730
11        13.0    1.517511   0.464806   1.336393
12        14.0    3.908106   1.196803   2.183501
13        15.0    1.269545   0.320960   1.023402
14        17.0    0.375032   0.160687   0.363430
15        18.0    1.370790   0.551087   1.860206
16        19.0    0.583288   0.218302   0.571101
17        20.0    0.828302   0.228803   0.981193
18        21.0    9.378191   2.752419  14.817126
19        23.0    1.532429   0.430545   2.226302
20        24.0    0.712883   0.212269   0.795172
21        25.0    1.159009   0.266359   1.291169
22        28.0    0.458248   0.124907   0.771783

In [23]:
df = ess[["cntry", "sclmeet", "rlgblg", "rlgdgr"]].groupby(by="cntry", as_index=False).mean()
df["cntry_name"] = df["cntry"].apply(lambda x: ess_cc[ess_cc["Value "] == x]["Category "].values[0])
df["cc"] = df["cntry_name"].apply(lambda x: name_to_id[x] if x in name_to_id else 0)
df = df[df["cc"] != 0]
df

   cntry   sclmeet    rlgblg    rlgdgr      cntry_name  cc
0     AT  4.922260  1.338573  5.151657         Austria  13
1     BE  5.190088  1.616060  4.376412         Belgium   1
2     BG  5.177311  1.281822  4.297901        Bulgaria  20
4     CY  4.005839  1.094891  7.064234          Cyprus  40
5     DE  4.935124  1.498347  4.052479         Germany   3
6     EE  4.212684  1.815159  4.207270         Estonia  22
7     ES  5.254338  1.445770  4.387202           Spain   5
8     FI  4.970569  1.529750  4.557262         Finland  14
9     FR  5.322417  1.561829  5.002259          France   6
10    GB  4.801663  1.614014  3.980998  United Kingdom  11
11    GR  4.263692  1.088865  6.716358          Greece   4
12    HR  5.458093  1.256558  6.058221         Croatia  31
13    HU  3.566100  1.384325  4.955619         Hungary  23
14    IE  4.265741  1.322261  5.395637         Ireland   7
17    IT  5.233159  1.309250  6.090052           Italy   8
18    LT  4.747253  1.282051  5.603663       Lithuania  25
19    LV  4.496006  1.634185  4.533546          Latvia  24
21    NL  5.493805  1.735103  4.224189     Netherlands  10
23    PL  4.395284  1.290569  6.831484          Poland  26
24    PT  5.627094  1.286963  6.077932        Portugal  12
26    SE  5.469919  1.685366  3.158537          Sweden  16
27    SI  4.949519  1.475160  5.547276        Slovenia  29
28    SK  4.832178  1.317614  7.409154        Slovakia  28

In [20]:
ess["cntryname"] = ess["cntry"].apply(lambda x: ess_cc[ess_cc["Value "] == x]["Category "].values[0])

C:\Users\Jinal\AppData\Local\Temp\ipykernel_11016\3915239163.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ess["cntryname"] = ess["cntry"].apply(lambda x: ess_cc[ess_cc["Value "] == x]["Category "].values[0])

In [ ]:
df_ess["sclmeet_wg"] = df_ess["sclmeet"] * df_ess["anweight"]
df_ess["rlgblg_wg"] = df_ess["rlgblg"] * df_ess["anweight"]
df_ess["rlgdgr_wg"] = df_ess["rlgdgr"] * df_ess["anweight"]

In [65]:
df = ess[["cntry", "sclmeet", "rlgblg", "rlgdgr", "sclmeet_wg", "rlgblg_wg", "rlgdgr_wg"]].groupby(by = "cntry", as_index=False).mean()
df.head()

  cntry   sclmeet    rlgblg    rlgdgr  sclmeet_wg  rlgblg_wg  rlgdgr_wg
0    AT  4.922260  1.338573  5.151657    1.656219   0.453005   1.621730
1    BE  5.190088  1.616060  4.376412    3.157097   0.991500   2.936396
2    BG  5.177311  1.281822  4.297901    1.269545   0.320960   1.023402
3    CH  5.222543  1.503613  4.986272    2.845744   0.813192   2.639653
4    CY  4.005839  1.094891  7.064234    0.458248   0.124907   0.771783

In [66]:
df.to_csv("ess_country_level_means.csv")